### ISSUE TITLE
Still no Configuration help on 3.6.6

### ISSUE THREAD

**Issue by Trilife** [UniversalDevicesInc-PG3/udi-poly-notification#49]
Just installed Notification (3.6.6)  on eISY (5.6.2) PG3x (3.1.27).

Trying to set it up, the Configuration Help is still not showing up.

Not sure if this helps: the MQTT NS by xKing seems to have a similar intermittent problem. On initial setup the EXPAND CONFIGURATION HELP button doesn't show and after a save, it all of a sudden pops up.

In the Notification case, the button is missing even after stop/start/restart...

Cheers

**Comment by jimboca** [comment]
All fixed and working now in 3.6.9.
