### ISSUE TITLE
If customized content ID is not sequential, remaining items do not show up

### ISSUE THREAD

**Issue by brianGit78** [UniversalDevicesInc-PG3/udi-poly-notification#51]
Noticed this while trying to troubleshoot why some new customizations were not showing up in message list. 

For example, I have Customizations, with automatically assigned IDs, 1 -4 and 6 -8. I had deleted customization with ID 5 in the past, and my node list now only shows customizations with IDs 1 - 4. If I add a new customization, it will fill in the gap as it will assign ID 5. But this does not always happen, especially if you delete a large group of customizations.

**Comment by jimboca** [comment]
Oh that's not good. I'll try to take a look soon.

**Comment by jimboca** [comment]
This is an Admin Console issue, nothing can be done in the nodeserver, please send a ticket to ask for a fix https://www.universal-devices.com/my-tickets
